//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicId" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicDescription" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}TitleHoldQueueLength" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}CurrentRequester" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}HoldingsSet" maxOccurs="unbounded"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}Problem" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibliographicId",
    "bibliographicDescription",
    "titleHoldQueueLength",
    "currentRequester",
    "holdingsSet",
    "problem"
})
@XmlRootElement(name = "BibInformation")
public class BibInformation {

    @XmlElement(name = "BibliographicId")
    protected BibliographicId bibliographicId;
    @XmlElement(name = "BibliographicDescription")
    protected BibliographicDescription bibliographicDescription;
    @XmlElement(name = "TitleHoldQueueLength", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigDecimal titleHoldQueueLength;
    @XmlElement(name = "CurrentRequester")
    protected List<CurrentRequester> currentRequester;
    @XmlElement(name = "HoldingsSet")
    protected List<HoldingsSet> holdingsSet;
    @XmlElement(name = "Problem")
    protected List<Problem> problem;

    /**
     * Gets the value of the bibliographicId property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicId }
     *     
     */
    public BibliographicId getBibliographicId() {
        return bibliographicId;
    }

    /**
     * Sets the value of the bibliographicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicId }
     *     
     */
    public void setBibliographicId(BibliographicId value) {
        this.bibliographicId = value;
    }

    /**
     * Gets the value of the bibliographicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicDescription }
     *     
     */
    public BibliographicDescription getBibliographicDescription() {
        return bibliographicDescription;
    }

    /**
     * Sets the value of the bibliographicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicDescription }
     *     
     */
    public void setBibliographicDescription(BibliographicDescription value) {
        this.bibliographicDescription = value;
    }

    /**
     * Gets the value of the titleHoldQueueLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getTitleHoldQueueLength() {
        return titleHoldQueueLength;
    }

    /**
     * Sets the value of the titleHoldQueueLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleHoldQueueLength(BigDecimal value) {
        this.titleHoldQueueLength = value;
    }

    /**
     * Gets the value of the currentRequester property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currentRequester property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurrentRequester().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrentRequester }
     * 
     * 
     */
    public List<CurrentRequester> getCurrentRequester() {
        if (currentRequester == null) {
            currentRequester = new ArrayList<CurrentRequester>();
        }
        return this.currentRequester;
    }

    /**
     * Gets the value of the holdingsSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the holdingsSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoldingsSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HoldingsSet }
     * 
     * 
     */
    public List<HoldingsSet> getHoldingsSet() {
        if (holdingsSet == null) {
            holdingsSet = new ArrayList<HoldingsSet>();
        }
        return this.holdingsSet;
    }

    /**
     * Gets the value of the problem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the problem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProblem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Problem }
     * 
     * 
     */
    public List<Problem> getProblem() {
        if (problem == null) {
            problem = new ArrayList<Problem>();
        }
        return this.problem;
    }

}
