//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicItemId"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicRecordId"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bibliographicItemId",
    "bibliographicRecordId",
    "ext"
})
@XmlRootElement(name = "BibliographicId")
public class BibliographicId {

    @XmlElement(name = "BibliographicItemId")
    protected BibliographicItemId bibliographicItemId;
    @XmlElement(name = "BibliographicRecordId")
    protected BibliographicRecordId bibliographicRecordId;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the bibliographicItemId property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicItemId }
     *     
     */
    public BibliographicItemId getBibliographicItemId() {
        return bibliographicItemId;
    }

    /**
     * Sets the value of the bibliographicItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicItemId }
     *     
     */
    public void setBibliographicItemId(BibliographicItemId value) {
        this.bibliographicItemId = value;
    }

    /**
     * Gets the value of the bibliographicRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicRecordId }
     *     
     */
    public BibliographicRecordId getBibliographicRecordId() {
        return bibliographicRecordId;
    }

    /**
     * Sets the value of the bibliographicRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicRecordId }
     *     
     */
    public void setBibliographicRecordId(BibliographicRecordId value) {
        this.bibliographicRecordId = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
