//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}InitiationHeader" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemId"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserId"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedReturned"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedNeverBorrowed"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedLost"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemReportedMissing"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemOptionalFields" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserOptionalFields" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}FiscalTransactionInformation" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "itemId",
    "userId",
    "itemReportedReturned",
    "itemReportedNeverBorrowed",
    "itemReportedLost",
    "itemReportedMissing",
    "itemOptionalFields",
    "userOptionalFields",
    "fiscalTransactionInformation",
    "ext"
})
@XmlRootElement(name = "CirculationStatusChangeReported")
public class CirculationStatusChangeReported {

    @XmlElement(name = "InitiationHeader")
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "ItemId", required = true)
    protected ItemId itemId;
    @XmlElement(name = "UserId", required = true)
    protected UserId userId;
    @XmlElement(name = "ItemReportedReturned")
    protected ItemReportedReturned itemReportedReturned;
    @XmlElement(name = "ItemReportedNeverBorrowed")
    protected ItemReportedNeverBorrowed itemReportedNeverBorrowed;
    @XmlElement(name = "ItemReportedLost")
    protected ItemReportedLost itemReportedLost;
    @XmlElement(name = "ItemReportedMissing")
    protected ItemReportedMissing itemReportedMissing;
    @XmlElement(name = "ItemOptionalFields")
    protected ItemOptionalFields itemOptionalFields;
    @XmlElement(name = "UserOptionalFields")
    protected UserOptionalFields userOptionalFields;
    @XmlElement(name = "FiscalTransactionInformation")
    protected FiscalTransactionInformation fiscalTransactionInformation;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link ItemId }
     *     
     */
    public ItemId getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemId }
     *     
     */
    public void setItemId(ItemId value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link UserId }
     *     
     */
    public UserId getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserId }
     *     
     */
    public void setUserId(UserId value) {
        this.userId = value;
    }

    /**
     * Gets the value of the itemReportedReturned property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedReturned }
     *     
     */
    public ItemReportedReturned getItemReportedReturned() {
        return itemReportedReturned;
    }

    /**
     * Sets the value of the itemReportedReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedReturned }
     *     
     */
    public void setItemReportedReturned(ItemReportedReturned value) {
        this.itemReportedReturned = value;
    }

    /**
     * Gets the value of the itemReportedNeverBorrowed property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedNeverBorrowed }
     *     
     */
    public ItemReportedNeverBorrowed getItemReportedNeverBorrowed() {
        return itemReportedNeverBorrowed;
    }

    /**
     * Sets the value of the itemReportedNeverBorrowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedNeverBorrowed }
     *     
     */
    public void setItemReportedNeverBorrowed(ItemReportedNeverBorrowed value) {
        this.itemReportedNeverBorrowed = value;
    }

    /**
     * Gets the value of the itemReportedLost property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedLost }
     *     
     */
    public ItemReportedLost getItemReportedLost() {
        return itemReportedLost;
    }

    /**
     * Sets the value of the itemReportedLost property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedLost }
     *     
     */
    public void setItemReportedLost(ItemReportedLost value) {
        this.itemReportedLost = value;
    }

    /**
     * Gets the value of the itemReportedMissing property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReportedMissing }
     *     
     */
    public ItemReportedMissing getItemReportedMissing() {
        return itemReportedMissing;
    }

    /**
     * Sets the value of the itemReportedMissing property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReportedMissing }
     *     
     */
    public void setItemReportedMissing(ItemReportedMissing value) {
        this.itemReportedMissing = value;
    }

    /**
     * Gets the value of the itemOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link ItemOptionalFields }
     *     
     */
    public ItemOptionalFields getItemOptionalFields() {
        return itemOptionalFields;
    }

    /**
     * Sets the value of the itemOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemOptionalFields }
     *     
     */
    public void setItemOptionalFields(ItemOptionalFields value) {
        this.itemOptionalFields = value;
    }

    /**
     * Gets the value of the userOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserOptionalFields }
     *     
     */
    public UserOptionalFields getUserOptionalFields() {
        return userOptionalFields;
    }

    /**
     * Sets the value of the userOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserOptionalFields }
     *     
     */
    public void setUserOptionalFields(UserOptionalFields value) {
        this.userOptionalFields = value;
    }

    /**
     * Gets the value of the fiscalTransactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public FiscalTransactionInformation getFiscalTransactionInformation() {
        return fiscalTransactionInformation;
    }

    /**
     * Sets the value of the fiscalTransactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalTransactionInformation }
     *     
     */
    public void setFiscalTransactionInformation(FiscalTransactionInformation value) {
        this.fiscalTransactionInformation = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
