//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}HoldingsSetId" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicDescription" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}Location" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}CallNumber" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}SummaryHoldingsInformation" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}ElectronicResource" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}ItemInformation" maxOccurs="unbounded"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}Problem" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "holdingsSetId",
    "bibliographicDescription",
    "location",
    "callNumber",
    "summaryHoldingsInformation",
    "electronicResource",
    "itemInformation",
    "ext",
    "problem"
})
@XmlRootElement(name = "HoldingsSet")
public class HoldingsSet {

    @XmlElement(name = "HoldingsSetId")
    protected String holdingsSetId;
    @XmlElement(name = "BibliographicDescription")
    protected BibliographicDescription bibliographicDescription;
    @XmlElement(name = "Location")
    protected Location location;
    @XmlElement(name = "CallNumber")
    protected String callNumber;
    @XmlElement(name = "SummaryHoldingsInformation")
    protected SummaryHoldingsInformation summaryHoldingsInformation;
    @XmlElement(name = "ElectronicResource")
    protected ElectronicResource electronicResource;
    @XmlElement(name = "ItemInformation")
    protected List<ItemInformation> itemInformation;
    @XmlElement(name = "Ext")
    protected Ext ext;
    @XmlElement(name = "Problem")
    protected List<Problem> problem;

    /**
     * Gets the value of the holdingsSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldingsSetId() {
        return holdingsSetId;
    }

    /**
     * Sets the value of the holdingsSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldingsSetId(String value) {
        this.holdingsSetId = value;
    }

    /**
     * Gets the value of the bibliographicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BibliographicDescription }
     *     
     */
    public BibliographicDescription getBibliographicDescription() {
        return bibliographicDescription;
    }

    /**
     * Sets the value of the bibliographicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibliographicDescription }
     *     
     */
    public void setBibliographicDescription(BibliographicDescription value) {
        this.bibliographicDescription = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the callNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallNumber() {
        return callNumber;
    }

    /**
     * Sets the value of the callNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallNumber(String value) {
        this.callNumber = value;
    }

    /**
     * Gets the value of the summaryHoldingsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryHoldingsInformation }
     *     
     */
    public SummaryHoldingsInformation getSummaryHoldingsInformation() {
        return summaryHoldingsInformation;
    }

    /**
     * Sets the value of the summaryHoldingsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryHoldingsInformation }
     *     
     */
    public void setSummaryHoldingsInformation(SummaryHoldingsInformation value) {
        this.summaryHoldingsInformation = value;
    }

    /**
     * Gets the value of the electronicResource property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicResource }
     *     
     */
    public ElectronicResource getElectronicResource() {
        return electronicResource;
    }

    /**
     * Sets the value of the electronicResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicResource }
     *     
     */
    public void setElectronicResource(ElectronicResource value) {
        this.electronicResource = value;
    }

    /**
     * Gets the value of the itemInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemInformation }
     * 
     * 
     */
    public List<ItemInformation> getItemInformation() {
        if (itemInformation == null) {
            itemInformation = new ArrayList<ItemInformation>();
        }
        return this.itemInformation;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

    /**
     * Gets the value of the problem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the problem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProblem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Problem }
     * 
     * 
     */
    public List<Problem> getProblem() {
        if (problem == null) {
            problem = new ArrayList<Problem>();
        }
        return this.problem;
    }

}
