//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}CallNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}CopyNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemDescriptionLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}HoldingsInformation" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}NumberOfPieces" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "callNumber",
    "copyNumber",
    "itemDescriptionLevel",
    "holdingsInformation",
    "numberOfPieces",
    "ext"
})
@XmlRootElement(name = "ItemDescription")
public class ItemDescription {

    @XmlElement(name = "CallNumber")
    protected String callNumber;
    @XmlElement(name = "CopyNumber")
    protected String copyNumber;
    @XmlElement(name = "ItemDescriptionLevel")
    protected SchemeValuePair itemDescriptionLevel;
    @XmlElement(name = "HoldingsInformation")
    protected HoldingsInformation holdingsInformation;
    @XmlElement(name = "NumberOfPieces", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "positiveInteger")
    protected BigDecimal numberOfPieces;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the callNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallNumber() {
        return callNumber;
    }

    /**
     * Sets the value of the callNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallNumber(String value) {
        this.callNumber = value;
    }

    /**
     * Gets the value of the copyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyNumber() {
        return copyNumber;
    }

    /**
     * Sets the value of the copyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyNumber(String value) {
        this.copyNumber = value;
    }

    /**
     * Gets the value of the itemDescriptionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getItemDescriptionLevel() {
        return itemDescriptionLevel;
    }

    /**
     * Sets the value of the itemDescriptionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setItemDescriptionLevel(SchemeValuePair value) {
        this.itemDescriptionLevel = value;
    }

    /**
     * Gets the value of the holdingsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link HoldingsInformation }
     *     
     */
    public HoldingsInformation getHoldingsInformation() {
        return holdingsInformation;
    }

    /**
     * Sets the value of the holdingsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldingsInformation }
     *     
     */
    public void setHoldingsInformation(HoldingsInformation value) {
        this.holdingsInformation = value;
    }

    /**
     * Gets the value of the numberOfPieces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getNumberOfPieces() {
        return numberOfPieces;
    }

    /**
     * Sets the value of the numberOfPieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPieces(BigDecimal value) {
        this.numberOfPieces = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
