//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 08:21:17 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}InitiationHeader" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}UserId"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}AuthenticationInput" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}LoanedItemsDesired" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}RequestedItemsDesired" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserFiscalAccountDesired" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initiationHeader",
    "userId",
    "authenticationInput",
    "userElementType",
    "loanedItemsDesired",
    "requestedItemsDesired",
    "userFiscalAccountDesired",
    "ext"
})
@XmlRootElement(name = "LookupUser")
public class LookupUser {

    @XmlElement(name = "InitiationHeader")
    protected InitiationHeader initiationHeader;
    @XmlElement(name = "UserId")
    protected UserId userId;
    @XmlElement(name = "AuthenticationInput")
    protected List<AuthenticationInput> authenticationInput;
    @XmlElement(name = "UserElementType")
    protected List<SchemeValuePair> userElementType;
    @XmlElement(name = "LoanedItemsDesired")
    protected LoanedItemsDesired loanedItemsDesired;
    @XmlElement(name = "RequestedItemsDesired")
    protected RequestedItemsDesired requestedItemsDesired;
    @XmlElement(name = "UserFiscalAccountDesired")
    protected UserFiscalAccountDesired userFiscalAccountDesired;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the initiationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InitiationHeader }
     *     
     */
    public InitiationHeader getInitiationHeader() {
        return initiationHeader;
    }

    /**
     * Sets the value of the initiationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitiationHeader }
     *     
     */
    public void setInitiationHeader(InitiationHeader value) {
        this.initiationHeader = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link UserId }
     *     
     */
    public UserId getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserId }
     *     
     */
    public void setUserId(UserId value) {
        this.userId = value;
    }

    /**
     * Gets the value of the authenticationInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticationInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticationInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticationInput }
     * 
     * 
     */
    public List<AuthenticationInput> getAuthenticationInput() {
        if (authenticationInput == null) {
            authenticationInput = new ArrayList<AuthenticationInput>();
        }
        return this.authenticationInput;
    }

    /**
     * Gets the value of the userElementType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userElementType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserElementType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeValuePair }
     * 
     * 
     */
    public List<SchemeValuePair> getUserElementType() {
        if (userElementType == null) {
            userElementType = new ArrayList<SchemeValuePair>();
        }
        return this.userElementType;
    }

    /**
     * Gets the value of the loanedItemsDesired property.
     * 
     * @return
     *     possible object is
     *     {@link LoanedItemsDesired }
     *     
     */
    public LoanedItemsDesired getLoanedItemsDesired() {
        return loanedItemsDesired;
    }

    /**
     * Sets the value of the loanedItemsDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanedItemsDesired }
     *     
     */
    public void setLoanedItemsDesired(LoanedItemsDesired value) {
        this.loanedItemsDesired = value;
    }

    /**
     * Gets the value of the requestedItemsDesired property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedItemsDesired }
     *     
     */
    public RequestedItemsDesired getRequestedItemsDesired() {
        return requestedItemsDesired;
    }

    /**
     * Sets the value of the requestedItemsDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedItemsDesired }
     *     
     */
    public void setRequestedItemsDesired(RequestedItemsDesired value) {
        this.requestedItemsDesired = value;
    }

    /**
     * Gets the value of the userFiscalAccountDesired property.
     * 
     * @return
     *     possible object is
     *     {@link UserFiscalAccountDesired }
     *     
     */
    public UserFiscalAccountDesired getUserFiscalAccountDesired() {
        return userFiscalAccountDesired;
    }

    /**
     * Sets the value of the userFiscalAccountDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFiscalAccountDesired }
     *     
     */
    public void setUserFiscalAccountDesired(UserFiscalAccountDesired value) {
        this.userFiscalAccountDesired = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
