//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 08:21:17 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ResponseHeader" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}Problem" maxOccurs="unbounded"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}UserId"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}UserFiscalAccount" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}LoanedItemsCount" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}LoanedItem" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}RequestedItemsCount" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}RequestedItem" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}UserOptionalFields" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "problem",
    "userId",
    "userFiscalAccount",
    "loanedItemsCount",
    "loanedItem",
    "requestedItemsCount",
    "requestedItem",
    "userOptionalFields",
    "ext"
})
@XmlRootElement(name = "LookupUserResponse")
public class LookupUserResponse {

    @XmlElement(name = "ResponseHeader")
    protected ResponseHeader responseHeader;
    @XmlElement(name = "Problem")
    protected List<Problem> problem;
    @XmlElement(name = "UserId")
    protected UserId userId;
    @XmlElement(name = "UserFiscalAccount")
    protected List<UserFiscalAccount> userFiscalAccount;
    @XmlElement(name = "LoanedItemsCount")
    protected List<LoanedItemsCount> loanedItemsCount;
    @XmlElement(name = "LoanedItem")
    protected List<LoanedItem> loanedItem;
    @XmlElement(name = "RequestedItemsCount")
    protected List<RequestedItemsCount> requestedItemsCount;
    @XmlElement(name = "RequestedItem")
    protected List<RequestedItem> requestedItem;
    @XmlElement(name = "UserOptionalFields")
    protected UserOptionalFields userOptionalFields;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseHeader }
     *     
     */
    public ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseHeader }
     *     
     */
    public void setResponseHeader(ResponseHeader value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the problem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the problem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProblem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Problem }
     * 
     * 
     */
    public List<Problem> getProblem() {
        if (problem == null) {
            problem = new ArrayList<Problem>();
        }
        return this.problem;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link UserId }
     *     
     */
    public UserId getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserId }
     *     
     */
    public void setUserId(UserId value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userFiscalAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userFiscalAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserFiscalAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserFiscalAccount }
     * 
     * 
     */
    public List<UserFiscalAccount> getUserFiscalAccount() {
        if (userFiscalAccount == null) {
            userFiscalAccount = new ArrayList<UserFiscalAccount>();
        }
        return this.userFiscalAccount;
    }

    /**
     * Gets the value of the loanedItemsCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanedItemsCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanedItemsCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanedItemsCount }
     * 
     * 
     */
    public List<LoanedItemsCount> getLoanedItemsCount() {
        if (loanedItemsCount == null) {
            loanedItemsCount = new ArrayList<LoanedItemsCount>();
        }
        return this.loanedItemsCount;
    }

    /**
     * Gets the value of the loanedItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanedItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanedItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanedItem }
     * 
     * 
     */
    public List<LoanedItem> getLoanedItem() {
        if (loanedItem == null) {
            loanedItem = new ArrayList<LoanedItem>();
        }
        return this.loanedItem;
    }

    /**
     * Gets the value of the requestedItemsCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedItemsCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedItemsCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedItemsCount }
     * 
     * 
     */
    public List<RequestedItemsCount> getRequestedItemsCount() {
        if (requestedItemsCount == null) {
            requestedItemsCount = new ArrayList<RequestedItemsCount>();
        }
        return this.requestedItemsCount;
    }

    /**
     * Gets the value of the requestedItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedItem }
     * 
     * 
     */
    public List<RequestedItem> getRequestedItem() {
        if (requestedItem == null) {
            requestedItem = new ArrayList<RequestedItem>();
        }
        return this.requestedItem;
    }

    /**
     * Gets the value of the userOptionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserOptionalFields }
     *     
     */
    public UserOptionalFields getUserOptionalFields() {
        return userOptionalFields;
    }

    /**
     * Sets the value of the userOptionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserOptionalFields }
     *     
     */
    public void setUserOptionalFields(UserOptionalFields value) {
        this.userOptionalFields = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
