//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ResponseHeader" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}Problem" maxOccurs="unbounded"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}AgencyId"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}OrganizationNameInformation" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}AgencyAddressInformation" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}AuthenticationPrompt" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}ApplicationProfileSupportedType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}ConsortiumAgreement" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}AgencyUserPrivilegeType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "problem",
    "agencyId",
    "organizationNameInformation",
    "agencyAddressInformation",
    "authenticationPrompt",
    "applicationProfileSupportedType",
    "consortiumAgreement",
    "agencyUserPrivilegeType",
    "ext"
})
@XmlRootElement(name = "LookupAgencyResponse")
public class LookupAgencyResponse {

    @XmlElement(name = "ResponseHeader")
    protected ResponseHeader responseHeader;
    @XmlElement(name = "Problem")
    protected List<Problem> problem;
    @XmlElement(name = "AgencyId")
    protected SchemeValuePair agencyId;
    @XmlElement(name = "OrganizationNameInformation")
    protected List<OrganizationNameInformation> organizationNameInformation;
    @XmlElement(name = "AgencyAddressInformation")
    protected List<AgencyAddressInformation> agencyAddressInformation;
    @XmlElement(name = "AuthenticationPrompt")
    protected List<AuthenticationPrompt> authenticationPrompt;
    @XmlElement(name = "ApplicationProfileSupportedType")
    protected List<SchemeValuePair> applicationProfileSupportedType;
    @XmlElement(name = "ConsortiumAgreement")
    protected List<SchemeValuePair> consortiumAgreement;
    @XmlElement(name = "AgencyUserPrivilegeType")
    protected List<SchemeValuePair> agencyUserPrivilegeType;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseHeader }
     *     
     */
    public ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseHeader }
     *     
     */
    public void setResponseHeader(ResponseHeader value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the problem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the problem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProblem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Problem }
     * 
     * 
     */
    public List<Problem> getProblem() {
        if (problem == null) {
            problem = new ArrayList<Problem>();
        }
        return this.problem;
    }

    /**
     * Gets the value of the agencyId property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getAgencyId() {
        return agencyId;
    }

    /**
     * Sets the value of the agencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setAgencyId(SchemeValuePair value) {
        this.agencyId = value;
    }

    /**
     * Gets the value of the organizationNameInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationNameInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationNameInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationNameInformation }
     * 
     * 
     */
    public List<OrganizationNameInformation> getOrganizationNameInformation() {
        if (organizationNameInformation == null) {
            organizationNameInformation = new ArrayList<OrganizationNameInformation>();
        }
        return this.organizationNameInformation;
    }

    /**
     * Gets the value of the agencyAddressInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agencyAddressInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgencyAddressInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgencyAddressInformation }
     * 
     * 
     */
    public List<AgencyAddressInformation> getAgencyAddressInformation() {
        if (agencyAddressInformation == null) {
            agencyAddressInformation = new ArrayList<AgencyAddressInformation>();
        }
        return this.agencyAddressInformation;
    }

    /**
     * Gets the value of the authenticationPrompt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticationPrompt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticationPrompt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticationPrompt }
     * 
     * 
     */
    public List<AuthenticationPrompt> getAuthenticationPrompt() {
        if (authenticationPrompt == null) {
            authenticationPrompt = new ArrayList<AuthenticationPrompt>();
        }
        return this.authenticationPrompt;
    }

    /**
     * Gets the value of the applicationProfileSupportedType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationProfileSupportedType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationProfileSupportedType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeValuePair }
     * 
     * 
     */
    public List<SchemeValuePair> getApplicationProfileSupportedType() {
        if (applicationProfileSupportedType == null) {
            applicationProfileSupportedType = new ArrayList<SchemeValuePair>();
        }
        return this.applicationProfileSupportedType;
    }

    /**
     * Gets the value of the consortiumAgreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consortiumAgreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsortiumAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeValuePair }
     * 
     * 
     */
    public List<SchemeValuePair> getConsortiumAgreement() {
        if (consortiumAgreement == null) {
            consortiumAgreement = new ArrayList<SchemeValuePair>();
        }
        return this.consortiumAgreement;
    }

    /**
     * Gets the value of the agencyUserPrivilegeType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agencyUserPrivilegeType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgencyUserPrivilegeType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeValuePair }
     * 
     * 
     */
    public List<SchemeValuePair> getAgencyUserPrivilegeType() {
        if (agencyUserPrivilegeType == null) {
            agencyUserPrivilegeType = new ArrayList<SchemeValuePair>();
        }
        return this.agencyUserPrivilegeType;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
