//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}InitiationHeader" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}MandatedAction" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}UserId"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}AuthenticationInput" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}ItemId" maxOccurs="unbounded"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}BibliographicId" maxOccurs="unbounded"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}ItemId" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}RequestId" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}RequestType"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}RequestScopeType"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemOptionalFields" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ShippingInformation" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}EarliestDateNeeded" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}NeedBeforeDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}PickupLocation" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}PickupExpiryDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}AcknowledgedFeeAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}PaidFeeAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}AcknowledgedItemUseRestrictionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}ItemElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UserElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "RequestItem")
public class RequestItem {

    @XmlElementRefs({
        @XmlElementRef(name = "ItemId", namespace = "http://www.niso.org/2008/ncip", type = ItemId.class),
        @XmlElementRef(name = "PickupLocation", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "RequestType", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "NeedBeforeDate", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "RequestId", namespace = "http://www.niso.org/2008/ncip", type = RequestId.class),
        @XmlElementRef(name = "AcknowledgedFeeAmount", namespace = "http://www.niso.org/2008/ncip", type = AcknowledgedFeeAmount.class),
        @XmlElementRef(name = "AuthenticationInput", namespace = "http://www.niso.org/2008/ncip", type = AuthenticationInput.class),
        @XmlElementRef(name = "UserId", namespace = "http://www.niso.org/2008/ncip", type = UserId.class),
        @XmlElementRef(name = "ItemOptionalFields", namespace = "http://www.niso.org/2008/ncip", type = ItemOptionalFields.class),
        @XmlElementRef(name = "ItemElementType", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "PickupExpiryDate", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "BibliographicId", namespace = "http://www.niso.org/2008/ncip", type = BibliographicId.class),
        @XmlElementRef(name = "ShippingInformation", namespace = "http://www.niso.org/2008/ncip", type = ShippingInformation.class),
        @XmlElementRef(name = "EarliestDateNeeded", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "RequestScopeType", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "UserElementType", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "AcknowledgedItemUseRestrictionType", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Ext", namespace = "http://www.niso.org/2008/ncip", type = Ext.class),
        @XmlElementRef(name = "PaidFeeAmount", namespace = "http://www.niso.org/2008/ncip", type = PaidFeeAmount.class),
        @XmlElementRef(name = "InitiationHeader", namespace = "http://www.niso.org/2008/ncip", type = InitiationHeader.class),
        @XmlElementRef(name = "MandatedAction", namespace = "http://www.niso.org/2008/ncip", type = MandatedAction.class)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ItemId" is used by two different parts of a schema. See: 
     * line 1531 of file:/home/kozlovsky/workspaces/ncip/xcncip2toolkit/core/trunk/binding/ilsdiv1_1/src/main/xsd/ncip_v2_02.xsd
     * line 1528 of file:/home/kozlovsky/workspaces/ncip/xcncip2toolkit/core/trunk/binding/ilsdiv1_1/src/main/xsd/ncip_v2_02.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemId }
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link RequestId }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link AuthenticationInput }
     * {@link AcknowledgedFeeAmount }
     * {@link UserId }
     * {@link ItemOptionalFields }
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link ShippingInformation }
     * {@link BibliographicId }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeValuePair }{@code >}
     * {@link Ext }
     * {@link PaidFeeAmount }
     * {@link MandatedAction }
     * {@link InitiationHeader }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
