//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}LocationWithinBuilding" minOccurs="0"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}HouseName" minOccurs="0"/>
 *             &lt;choice>
 *               &lt;element ref="{http://www.niso.org/2008/ncip}District"/>
 *               &lt;sequence>
 *                 &lt;element ref="{http://www.niso.org/2008/ncip}PostOfficeBox"/>
 *                 &lt;element ref="{http://www.niso.org/2008/ncip}District" minOccurs="0"/>
 *               &lt;/sequence>
 *               &lt;sequence>
 *                 &lt;element ref="{http://www.niso.org/2008/ncip}Street"/>
 *                 &lt;element ref="{http://www.niso.org/2008/ncip}PostOfficeBox" minOccurs="0"/>
 *                 &lt;element ref="{http://www.niso.org/2008/ncip}District" minOccurs="0"/>
 *               &lt;/sequence>
 *             &lt;/choice>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}Line1"/>
 *             &lt;element ref="{http://www.niso.org/2008/ncip}Line2" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Locality" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Region" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Country" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}PostalCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}CareOf" minOccurs="0"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "StructuredAddress")
public class StructuredAddress {

    @XmlElementRefs({
        @XmlElementRef(name = "PostalCode", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Line2", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Region", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "HouseName", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "LocationWithinBuilding", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Locality", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Line1", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "District", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Ext", namespace = "http://www.niso.org/2008/ncip", type = Ext.class),
        @XmlElementRef(name = "CareOf", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Country", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "PostOfficeBox", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class),
        @XmlElementRef(name = "Street", namespace = "http://www.niso.org/2008/ncip", type = JAXBElement.class)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "District" is used by two different parts of a schema. See: 
     * line 2938 of file:/home/kozlovsky/workspaces/ncip/xcncip2toolkit/core/trunk/binding/ilsdiv1_1/src/main/xsd/ncip_v2_02.xsd
     * line 2935 of file:/home/kozlovsky/workspaces/ncip/xcncip2toolkit/core/trunk/binding/ilsdiv1_1/src/main/xsd/ncip_v2_02.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Ext }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
