//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 08:21:17 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UnstructuredAddressType"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}UnstructuredAddressData"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unstructuredAddressType",
    "unstructuredAddressData",
    "ext"
})
@XmlRootElement(name = "UnstructuredAddress")
public class UnstructuredAddress {

    @XmlElement(name = "UnstructuredAddressType", required = true)
    protected SchemeValuePair unstructuredAddressType;
    @XmlElement(name = "UnstructuredAddressData", required = true)
    protected String unstructuredAddressData;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the unstructuredAddressType property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getUnstructuredAddressType() {
        return unstructuredAddressType;
    }

    /**
     * Sets the value of the unstructuredAddressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setUnstructuredAddressType(SchemeValuePair value) {
        this.unstructuredAddressType = value;
    }

    /**
     * Gets the value of the unstructuredAddressData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnstructuredAddressData() {
        return unstructuredAddressData;
    }

    /**
     * Sets the value of the unstructuredAddressData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnstructuredAddressData(String value) {
        this.unstructuredAddressData = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
