//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:59:27 PM CEST 
//


package org.extensiblecatalog.ncip.v2.binding.ilsdiv1_1.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}NoticeType"/>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}NoticeContent" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}NoticeItem" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}UserFiscalAccount"/>
 *           &lt;element ref="{http://www.niso.org/2008/ncip}UserPrivilege"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.niso.org/2008/ncip}Ext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noticeType",
    "noticeContent",
    "noticeItem",
    "userFiscalAccount",
    "userPrivilege",
    "ext"
})
@XmlRootElement(name = "UserNoticeDetails")
public class UserNoticeDetails {

    @XmlElement(name = "NoticeType", required = true)
    protected SchemeValuePair noticeType;
    @XmlElement(name = "NoticeContent")
    protected String noticeContent;
    @XmlElement(name = "NoticeItem")
    protected List<NoticeItem> noticeItem;
    @XmlElement(name = "UserFiscalAccount")
    protected UserFiscalAccount userFiscalAccount;
    @XmlElement(name = "UserPrivilege")
    protected UserPrivilege userPrivilege;
    @XmlElement(name = "Ext")
    protected Ext ext;

    /**
     * Gets the value of the noticeType property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeValuePair }
     *     
     */
    public SchemeValuePair getNoticeType() {
        return noticeType;
    }

    /**
     * Sets the value of the noticeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeValuePair }
     *     
     */
    public void setNoticeType(SchemeValuePair value) {
        this.noticeType = value;
    }

    /**
     * Gets the value of the noticeContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * Sets the value of the noticeContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoticeContent(String value) {
        this.noticeContent = value;
    }

    /**
     * Gets the value of the noticeItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noticeItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoticeItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoticeItem }
     * 
     * 
     */
    public List<NoticeItem> getNoticeItem() {
        if (noticeItem == null) {
            noticeItem = new ArrayList<NoticeItem>();
        }
        return this.noticeItem;
    }

    /**
     * Gets the value of the userFiscalAccount property.
     * 
     * @return
     *     possible object is
     *     {@link UserFiscalAccount }
     *     
     */
    public UserFiscalAccount getUserFiscalAccount() {
        return userFiscalAccount;
    }

    /**
     * Sets the value of the userFiscalAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFiscalAccount }
     *     
     */
    public void setUserFiscalAccount(UserFiscalAccount value) {
        this.userFiscalAccount = value;
    }

    /**
     * Gets the value of the userPrivilege property.
     * 
     * @return
     *     possible object is
     *     {@link UserPrivilege }
     *     
     */
    public UserPrivilege getUserPrivilege() {
        return userPrivilege;
    }

    /**
     * Sets the value of the userPrivilege property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPrivilege }
     *     
     */
    public void setUserPrivilege(UserPrivilege value) {
        this.userPrivilege = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link Ext }
     *     
     */
    public Ext getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ext }
     *     
     */
    public void setExt(Ext value) {
        this.ext = value;
    }

}
